/**************************************************************************************************
 * project
 * Description - Sys9804 - WebService Consumer-PERCI
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys9804;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseAction;

public class Sys9804Action extends BaseAction {
	@Autowired
	private Sys9804Biz biz;

	public String getDefault() throws Exception {
		biz.getDefault(paramEntity);
		return "list";
	}

	public String getList() throws Exception {
		try {
			biz.getList(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String getDetail() throws Exception {
		biz.getDetail(paramEntity);
		return "detail";
	}
}