/**************************************************************************************************
 * Project
 * Description - MyTimesheet - My Timesheet
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.tms;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseAction;

public class TimesheetAction extends BaseAction {
	@Autowired
	private TimesheetBiz biz;

	public String mytimesheets() throws Exception {
		biz.myTimesheet(paramEntity);
		return "myTimesheet";
	}
}