/**************************************************************************************************
 * Project
 * Description - MyTimesheet - My Timesheet
 *	- Generated by Source Generator
 *************************************************************************************************/
package com.es.portal.ipro.timesheet;

import org.springframework.beans.factory.annotation.Autowired;

import com.es.portal.common.extend.BaseAction;

public class TimesheetAction extends BaseAction {
	@Autowired
	private TimesheetBiz biz;

	public String mytimesheets() throws Exception {
		biz.mytimesheets(paramEntity);
		return "myTimesheet";
	}

	public String getAssignmentInfo() throws Exception {
		try {
			biz.getAssignmentInfo(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String getTimesheetPeriod() throws Exception {
		try {
			biz.getTimesheetPeriod(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String getTimesheetDetail() throws Exception {
		try {
			biz.getTimesheetDetail(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}
}