/**************************************************************************************************
 * Project
 * Description - MyTimesheet - My Timesheet
 *	- Generated by Source Generator
 *************************************************************************************************/
package com.es.portal.ipro.timesheet;

import org.springframework.beans.factory.annotation.Autowired;

import com.es.portal.common.extend.BaseAction;

public class TimesheetAction extends BaseAction {
	@Autowired
	private TimesheetBiz biz;

	public String mytimesheets() throws Exception {
		biz.mytimesheets(paramEntity);
		return "myTimesheet";
	}
}