/**************************************************************************************************
 * project
 * Description - Bbs0202 - Notice
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.bbs.bbs0202;

import zebra.data.ParamEntity;

public interface Bbs0202Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getAttachedFile(ParamEntity paramEntity) throws Exception;
}