<%/************************************************************************************************
* Description - Sys0204 - Country / Currency Code
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	SysCountryCurrency sysCountryCurrency = (SysCountryCurrency)paramEntity.getObject("sysCountryCurrency");
	String dateFormat = ConfigUtil.getProperty("format.date.java");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var countryCurrencyId = "<%=sysCountryCurrency.getCountryCurrencyId()%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnSave" caption="button.com.save" iconClass="fa-save"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table class="tblEdit">
		<caption class="captionEdit"><mc:msg key="sys0204.caption.currency"/></caption>
		<colgroup>
			<col width="15%"/>
			<col width="35%"/>
			<col width="15%"/>
			<col width="35%"/>
		</colgroup>
		<tr>
			<th class="thEdit Rt mandatory"><mc:msg key="sys0204.header.currencyName"/></th>
			<td class="tdEdit"><ui:text name="currencyName" value="<%=sysCountryCurrency.getCurrencyName()%>" checkName="sys0204.header.currencyName" options="mandatory"/></td>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.currencySymbol"/></th>
			<td class="tdEdit"><ui:text name="currencySymbol" value="<%=sysCountryCurrency.getCurrencySymbol()%>" maxlength="10" checkName="sys0204.header.currencySymbol"/></td>
		</tr>
		<tr>
			<th class="thEdit Rt mandatory"><mc:msg key="sys0204.header.currencyAlphaCode"/></th>
			<td class="tdEdit"><ui:text name="currencyAlphabeticCode" value="<%=sysCountryCurrency.getCurrencyAlphabeticCode()%>" maxlength="5" style="text-transform:uppercase;" checkName="sys0204.header.currencyAlphaCode" options="mandatory"/></td>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.currencyNumCode"/></th>
			<td class="tdEdit"><ui:text name="currencyNumericCode" value="<%=sysCountryCurrency.getCurrencyNumericCode()%>" maxlength="5" checkName="sys0204.header.currencyNumCode"/></td>
		</tr>
	</table>
	<div class="horGap10"></div>
	<table class="tblEdit">
		<caption class="captionEdit"><mc:msg key="sys0204.caption.country"/></caption>
		<colgroup>
			<col width="15%"/>
			<col width="35%"/>
			<col width="15%"/>
			<col width="35%"/>
		</colgroup>
		<tr>
			<th class="thEdit Rt mandatory"><mc:msg key="sys0204.header.countryName"/></th>
			<td class="tdEdit"><ui:text name="countryName" value="<%=sysCountryCurrency.getCountryName()%>" checkName="sys0204.header.countryName" options="mandatory"/></td>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.countryLangCode"/></th>
			<td class="tdEdit"><ui:text name="countryLanguageCode" value="<%=sysCountryCurrency.getCountryLanguageCode()%>" maxlength="5" checkName="sys0204.header.countryLangCode"/></td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.countryCode2"/></th>
			<td class="tdEdit"><ui:text name="countryCode2" value="<%=sysCountryCurrency.getCountryCode2()%>" maxlength="5" style="text-transform:uppercase;" checkName="sys0204.header.countryCode2"/></td>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.countryCode3"/></th>
			<td class="tdEdit"><ui:text name="countryCode3" value="<%=sysCountryCurrency.getCountryCode3()%>" maxlength="5" style="text-transform:uppercase;" checkName="sys0204.header.countryCode3"/></td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.countryNumCode"/></th>
			<td class="tdEdit"><ui:text name="countryNumericCode" value="<%=sysCountryCurrency.getCountryNumericCode()%>" maxlength="5" checkName="sys0204.header.countryNumCode"/></td>
			<th class="thEdit Rt"></th>
			<td class="tdEdit"></td>
		</tr>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>