<%/************************************************************************************************
* Description - Sys0204 - Country / Currency Code
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet resultDataSet = (DataSet)paramEntity.getObject("resultDataSet");
	SysCountryCurrency sysCountryCurrency = (SysCountryCurrency)paramEntity.getObject("sysCountryCurrency");
	String dateFormat = ConfigUtil.getProperty("format.date.java");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var countryCurrencyId = "<%=sysCountryCurrency.getCountryCurrencyId()%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnEdit" caption="button.com.edit" iconClass="fa-edit"/>
			<ui:button id="btnDelete" caption="button.com.delete" iconClass="fa-save"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table class="tblEdit">
		<caption class="captionEdit"><mc:msg key="sys0204.caption.currency"/></caption>
		<colgroup>
			<col width="15%"/>
			<col width="35%"/>
			<col width="15%"/>
			<col width="35%"/>
		</colgroup>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.currencyName"/></th>
			<td class="tdEdit"><%=sysCountryCurrency.getCurrencyName()%></td>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.currencySymbol"/></th>
			<td class="tdEdit"><%=sysCountryCurrency.getCurrencySymbol()%></td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.currencyAlphaCode"/></th>
			<td class="tdEdit"><%=sysCountryCurrency.getCurrencyAlphabeticCode()%></td>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.currencyNumCode"/></th>
			<td class="tdEdit"><%=sysCountryCurrency.getCurrencyNumericCode()%></td>
		</tr>
	</table>
	<div class="horGap10"></div>
	<table class="tblEdit">
		<caption class="captionEdit"><mc:msg key="sys0204.caption.country"/></caption>
		<colgroup>
			<col width="15%"/>
			<col width="35%"/>
			<col width="15%"/>
			<col width="35%"/>
		</colgroup>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.countryName"/></th>
			<td class="tdEdit"><%=sysCountryCurrency.getCountryName()%></td>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.countryLangCode"/></th>
			<td class="tdEdit"><%=sysCountryCurrency.getCountryLanguageCode()%></td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.countryCode2"/></th>
			<td class="tdEdit"><%=sysCountryCurrency.getCountryCode2()%></td>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.countryCode3"/></th>
			<td class="tdEdit"><%=sysCountryCurrency.getCountryCode3()%></td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sys0204.header.countryNumCode"/></th>
			<td class="tdEdit" colspan="3"><%=sysCountryCurrency.getCountryNumericCode()%></td>
		</tr>
	</table>
	<div class="horGap10"></div>
	<table class="tblEdit">
		<caption class="captionEdit"><mc:msg key="sys0204.caption.basic"/></caption>
		<colgroup>
			<col width="15%"/>
			<col width="35%"/>
			<col width="15%"/>
			<col width="35%"/>
		</colgroup>
		<tr>
			<th class="thEdit Rt"><mc:msg key="page.com.insertUser"/></th>
			<td class="tdEdit"><%=sysCountryCurrency.getInsertUserName()%></td>
			<th class="thEdit Rt"><mc:msg key="page.com.insertDate"/></th>
			<td class="tdEdit"><%=CommonUtil.toString(sysCountryCurrency.getInsertDate(), dateFormat)%></td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="page.com.updateUser"/></th>
			<td class="tdEdit"><%=sysCountryCurrency.getUpdateUserName()%></td>
			<th class="thEdit Rt"><mc:msg key="page.com.updateDate"/></th>
			<td class="tdEdit"><%=CommonUtil.toString(sysCountryCurrency.getUpdateDate(), dateFormat)%></td>
		</tr>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>