<%/************************************************************************************************
* Description - Sys9804 - WebService Consumer-PERCI
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity pe = (ParamEntity)request.getAttribute("paramEntity");
	DataSet detail = (DataSet)pe.getObject("invoiceDetailList");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea" class="areaContainerPopup">
	<table class="tblEdit">
		<colgroup>
			<col width="18%"/>
			<col width="32%"/>
			<col width="18%"/>
			<col width="32%"/>
		</colgroup>
		<tr>
			<th class="thEdit rt">Invoice Number</th>
			<td class="tdEdit"><%=pe.getObject("invoiceNumber")%></td>
			<th class="thEdit rt">Invoice Date</th>
			<td class="tdEdit"><%=pe.getObject("invoiceDate")%></td>
		</tr>
		<tr>
			<th class="thEdit rt">Start Date</th>
			<td class="tdEdit"><%=pe.getObject("startDate")%></td>
			<th class="thEdit rt">End Date</th>
			<td class="tdEdit"><%=pe.getObject("endDate")%></td>
		</tr>
		<tr>
			<th class="thEdit rt">Gst Amount</th>
			<td class="tdEdit"><%=CommonUtil.toString((double)pe.getObject("gstAmount"), "#,###.##")%></td>
			<th class="thEdit rt">Total Billable</th>
			<td class="tdEdit"><%=CommonUtil.toString((double)pe.getObject("totalBillable"), "#,###.##")%></td>
		</tr>
	</table>
</div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table id="tblGrid" class="tblGrid">
		<colgroup>
			<col width="*"/>
			<col width="12%"/>
			<col width="25%"/>
			<col width="16%"/>
			<col width="20%"/>
		</colgroup>
		<thead>
			<tr>
				<th class="thGrid">Ipro Name</th>
				<th class="thGrid">Cost Center</th>
				<th class="thGrid">Reference</th>
				<th class="thGrid">Billable Amount</th>
				<th class="thGrid">State</th>
			</tr>
		</thead>
		<tbody id="tblGridBody">
<%
		if (detail.getRowCnt() > 0) {
			for (int i=0; i<detail.getRowCnt(); i++) {
%>
			<tr>
				<td class="tdGrid"><%=detail.getValue(i, "iproName")%></td>
				<td class="tdGrid ct"><%=CommonUtil.replace(detail.getValue(i, "costCenter"), "null", "")%></td>
				<td class="tdGrid"><%=detail.getValue(i, "reference")%></td>
				<td class="tdGrid rt"><%=CommonUtil.toString(CommonUtil.toDouble(detail.getValue(i, "billableAmount")), "#,###.00")%></td>
				<td class="tdGrid"><%=detail.getValue(i, "state")%></td>
			</tr>
<%
			}
		} else {
%>
			<tr>
				<td class="tdGrid Ct" colspan="5"><mc:msg key="I002"/></td>
			</tr>
<%
		}
%>
		</tbody>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>