/**************************************************************************************************
 * project
 * Description - Sys0408 - Menu - Authority Group
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys0408;

import zebra.data.ParamEntity;

public interface Sys0408Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeInsert(ParamEntity paramEntity) throws Exception;
}