/**************************************************************************************************
 * Project
 * Description - MyTimesheet - My Timesheet
 *	- Generated by Source Generator
 *************************************************************************************************/
package com.es.portal.corporate.ipro;

import org.springframework.beans.factory.annotation.Autowired;

import com.es.portal.common.extend.BaseAction;

public class IproAction extends BaseAction {
	@Autowired
	private IproBiz biz;

	public String myipros() throws Exception {
		biz.myIpros(paramEntity);
		return "myIpro";
	}

	public String getIproList() throws Exception {
		try {
			biz.getIproList(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String newIpro() throws Exception {
		biz.newIpro(paramEntity);
		return "newIpro";
	}

	public String exeExport() throws Exception {
		biz.exeExport(paramEntity);
		setRequestAttribute("paramEntity", paramEntity);
		return "export";
	}
}